steps:
  - name: 'golang:1.16-buster'
    entrypoint: 'go'
    args: ['build', '.']
  - name: 'gcr.io/kaniko-project/executor:v1.6.0'
    args:
      - --destination=asia-northeast1-docker.pkg.dev/$PROJECT_ID/cloudrun-helloworld/${_BRANCH_NAME}:${_COMMIT_SHA}
      - --cache=true
      - --cache-ttl=6h
substitutions:
  _BRANCH_NAME: sample_branch
  _COMMIT_SHA: sample_sha