steps:
  - name: 'golang:1.15-buster'
    entrypoint: 'go'
    args: ['build', '.']
    env: ['GO111MODULE=on']
  - name: 'gcr.io/kaniko-project/executor:v1.3.0'
    args:
      - --destination=asia-northeast1-docker.pkg.dev/$PROJECT_ID/cloudrun-helloworld/local:test
      - --cache=true
      - --cache-ttl=6h