steps:
  - name: 'golang:1.20-bullseye'
    entrypoint: 'go'
    args: ['build', '-o', 'app', './cmd/server']
    env: ['CGO_ENABLED=0']
  - name: 'gcr.io/kaniko-project/executor:v1.9.1'
    args:
      - --destination=asia-northeast1-docker.pkg.dev/$PROJECT_ID/cloudrun-helloworld/main:$BRANCH_NAME
      - --destination=asia-northeast1-docker.pkg.dev/$PROJECT_ID/cloudrun-helloworld/main:$COMMIT_SHA
      - --cache=true
      - --cache-ttl=6h