steps:
  - name: 'golang:1.16-buster'
    entrypoint: 'go'
    args: ['build', '.']
  - name: 'gcr.io/kaniko-project/executor:v1.6.0'
    args:
      - --destination=asia-northeast1-docker.pkg.dev/$PROJECT_ID/cloudrun-helloworld/$BRANCH_NAME:$COMMIT_SHA
      - --cache=true
      - --cache-ttl=6h
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk:slim'
    entrypoint: 'gcloud'
    waitFor: ['gobuild']
    args:
      - beta
      - run
      - deploy
      - cloudrun_hellowrold
      - --region=asia-northeast1
      - --platform=managed
      - --max-instances=1
      - --cpu=1
      - --memory=256M
      - --concurrency=8
      - --image=asia-northeast1-docker.pkg.dev/$PROJECT_ID/cloudrun-helloworld/$BRANCH_NAME:$COMMIT_SHA