name: "deploy"
on: push
  
jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write'
      issues: 'write'
      checks: 'write'
      pull-requests: 'write'
      statuses: 'write'
    steps:
      - name: "Check for Command"
        id: command
        uses: xt0rted/slash-command-action@065da288bcfe24ff96b3364c7aac1f6dca0fb027 #1.1.0
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          command: deploy
          reaction: "true"
          reaction-type: "eyes"
          allow-edits: "true"

      - name: "Get branch name"
        uses: xt0rted/pull-request-comment-branch@29fe0354c01b30fb3de76f193ab33abf8fe5ddb0 #1.2.0
        id: comment-branch
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}

      - name: "Checkout"
        uses: actions/checkout@v2
        with:
          ref: ${{ steps.get_branch.outputs.head_ref }}

      - name: "Post Comment"
        uses: actions/github-script@v3
        env:
          MESSAGE: |
            Start Deploy to ${{ steps.command.outputs.command-arguments }}
            Branch: ${{ steps.comment-branch.outputs.head_ref }}
            Commit: ${{ steps.comment-branch.outputs.head_sha }}
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            github.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: process.env.MESSAGE
            })
      - name: "Google Auth"
        uses: "google-github-actions/auth@v0"
        with:
          workload_identity_provider: "projects/${{ secrets.PROJECT_NUMBER }}/locations/global/workloadIdentityPools/github-actions/providers/gha-provider"
          service_account: "github@${{ secrets.GCP_PROJECT }}.iam.gserviceaccount.com"
      - name: 'Set up Cloud SDK'
        uses: 'google-github-actions/setup-gcloud@v0'
        with:
          version: '369.0.0'
      - name: 'Use gcloud CLI'
        run: 'gcloud info'
      - name: 'cloud build submit'
        run: 'gcloud builds submit --config cloudbuild.yaml'
